#![deny(unsafe_code)]
use serde::{Deserialize, Serialize};

pub type BlockId = String;

/// Every block MUST have a DB entity reference. No Option<> wrapper.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct NomtuRef {
    pub id: String,
    pub word: String,
    pub kind: String,
}

impl NomtuRef {
    pub fn new(id: impl Into<String>, word: impl Into<String>, kind: impl Into<String>) -> Self {
        Self { id: id.into(), word: word.into(), kind: kind.into() }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BlockMeta {
    pub created_at: u64,
    pub updated_at: u64,
    pub author: String,
    pub version: u32,
}

impl Default for BlockMeta {
    fn default() -> Self {
        Self { created_at: 0, updated_at: 0, author: String::new(), version: 1 }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BlockModel {
    pub id: BlockId,
    pub entity: NomtuRef,          // NON-OPTIONAL: blocks without DB entity do not exist
    pub flavour: String,
    pub slots: Vec<(String, crate::slot::SlotValue)>,
    pub children: Vec<BlockId>,
    pub meta: BlockMeta,
    pub parent: Option<BlockId>,
}

impl BlockModel {
    pub fn new(id: impl Into<String>, entity: NomtuRef, flavour: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            entity,
            flavour: flavour.into(),
            slots: Vec::new(),
            children: Vec::new(),
            meta: BlockMeta::default(),
            parent: None,
        }
    }

    pub fn get_slot(&self, name: &str) -> Option<&crate::slot::SlotValue> {
        self.slots.iter().find(|(k, _)| k == name).map(|(_, v)| v)
    }

    pub fn set_slot(&mut self, name: impl Into<String>, value: crate::slot::SlotValue) {
        let name = name.into();
        if let Some(entry) = self.slots.iter_mut().find(|(k, _)| *k == name) {
            entry.1 = value;
        } else {
            self.slots.push((name, value));
        }
    }

    pub fn insert(entity: NomtuRef, flavour: impl Into<String>, dict: &dyn crate::dict_reader::DictReader) -> Self {
        let kind = entity.kind.clone();
        debug_assert!(dict.is_known_kind(&kind), "Unknown grammar kind: {kind}");
        let id = uuid_v4();
        Self::new(id, entity, flavour)
    }
}

fn uuid_v4() -> String {
    // Simple deterministic ID for Wave B — real UUID in Wave C
    use std::time::{SystemTime, UNIX_EPOCH};
    let t = SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_nanos();
    format!("{:032x}", t)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dict_reader::DictReader;
    use crate::stub_dict::StubDictReader;

    #[test]
    fn block_model_has_entity() {
        let entity = NomtuRef::new("id1", "summarize", "verb");
        let reader = StubDictReader::with_kinds(&["verb"]);
        let block = BlockModel::insert(entity.clone(), "affine:paragraph", &reader);
        assert_eq!(block.entity.kind, "verb");
        assert_eq!(block.entity.word, "summarize");
    }

    #[test]
    fn block_model_slots() {
        let mut block = BlockModel::new("id1", NomtuRef::new("id1", "w", "k"), "affine:paragraph");
        block.set_slot("text", crate::slot::SlotValue::Text("Hello".into()));
        assert!(block.get_slot("text").is_some());
        assert!(block.get_slot("missing").is_none());
    }

    /// Blueprint invariant: entity field is non-optional — BlockModel::new requires a concrete NomtuRef.
    #[test]
    fn block_model_nomtu_ref_required() {
        let entity = NomtuRef::new("eid", "plan", "concept");
        let block = BlockModel::new("blk1", entity, "affine:note");
        // Structural guarantee: entity is always present, not Option<NomtuRef>
        assert_eq!(block.entity.id, "eid");
        assert_eq!(block.entity.word, "plan");
        assert_eq!(block.entity.kind, "concept");
    }

    /// BlockModel::new with valid args succeeds and fields are populated correctly.
    #[test]
    fn block_model_valid_creates() {
        let entity = NomtuRef::new("e42", "render", "verb");
        let block = BlockModel::new("b42", entity, "affine:paragraph");
        assert_eq!(block.id, "b42");
        assert_eq!(block.flavour, "affine:paragraph");
        assert!(block.slots.is_empty());
        assert!(block.children.is_empty());
        assert!(block.parent.is_none());
        assert_eq!(block.meta.version, 1);
    }

    /// uuid_v4-based IDs generated by insert() are distinct across two successive calls.
    #[test]
    fn block_id_is_unique() {
        let dict = StubDictReader::new();
        let e1 = NomtuRef::new("e1", "fetch", "verb");
        let e2 = NomtuRef::new("e2", "store", "verb");
        let b1 = BlockModel::insert(e1, "affine:paragraph", &dict);
        let b2 = BlockModel::insert(e2, "affine:paragraph", &dict);
        assert_ne!(b1.id, b2.id, "Two successive insert() calls must produce distinct IDs");
    }

    /// NomtuRef id field round-trips through a hex-format string (matching uuid_v4 format).
    #[test]
    fn nomtu_ref_id_roundtrips() {
        let hex_id = format!("{:032x}", 0xcafe_u64);
        let r = NomtuRef::new(hex_id.clone(), "cafe", "concept");
        assert_eq!(r.id, hex_id);
        // Parse back to confirm it is valid hex
        let parsed = u64::from_str_radix(r.id.trim_start_matches('0'), 16).unwrap_or(0);
        assert_eq!(parsed, 0xcafe_u64);
    }
}
