pub mod ad_creative;
pub mod app;
pub mod app_bundle;
pub mod audio;
pub mod code_exec;
pub mod data;
pub mod data_extract;
pub mod data_frame;
pub mod data_query;
pub mod document;
pub mod embed_gen;
pub mod export;
pub mod image;
pub mod mesh;
pub mod mobile_screen;
pub mod native_screen;
pub mod pipeline;
pub mod presentation;
pub mod rag_query;
pub mod render;
pub mod scenario;
pub mod scenario_workflow;
pub mod storyboard;
pub mod transform;
pub mod video;
pub mod web_screen;
pub mod workflow;

/// Uniform error-wrapping return type for safe compose wrappers.
pub type ComposeResult = Result<(), String>;
