/// Integration test for the AV1 video codec (§5.16.13 order #6 — §4.4.6 canonical video format).
///
/// Verifies:
///  1. `ingest_av1` parses the fixture and returns correct metadata.
///  2. `verify_av1_roundtrip` confirms the round-trip gate passes.
///  3. Two back-to-back `ingest_av1` calls on the same bytes produce
///     byte-identical `canonical_bytes` (determinism of the identity-map encoder).
///  4. `ingest_av1` rejects garbage input.
///  5. `ingest_av1` rejects IVF with a non-AV01 codec fourcc.
///
/// # Encoder status note
///
/// `canonical_bytes` is currently an identity copy of the input (no pure-Rust
/// AV1 video decoder is available on Windows without nasm/FFI as of §5.16.13
/// order #6). The round-trip gate asserts frame_count equality only. These tests
/// will be updated when a decoder + ravif-loop re-encode path lands.
///
/// # Fixture generation
///
/// `tiny.av1.ivf` is a hand-crafted 74-byte IVF file containing 3 frames of
/// minimal Temporal Delimiter OBU bytes (0x12 0x00). Generated by a small Rust
/// build script (not ffmpeg) since ffmpeg was not present in the CI environment.
/// The IVF container is valid; the AV1 OBU payload is syntactically minimal
/// (not a semantically complete bitstream). The IVF parser accepts it, which
/// is sufficient for metadata extraction and the identity-mapped round-trip.

use nom_media::{ingest_av1, verify_av1_roundtrip};

/// 3-frame AV1-IVF fixture: DKIF signature, AV01 codec, 16×16, 2fps, 3 frames
/// of Temporal Delimiter OBU (0x12 0x00). Hand-crafted, 74 bytes total.
static TINY_AV1_IVF: &[u8] = include_bytes!("fixtures/tiny.av1.ivf");

#[test]
fn ingest_av1_returns_correct_metadata() {
    let result = ingest_av1(TINY_AV1_IVF).expect("ingest_av1 should succeed on a valid IVF");
    assert_eq!(result.width, 16, "expected width 16");
    assert_eq!(result.height, 16, "expected height 16");
    assert_eq!(result.frame_count, 3, "expected 3 frames");
    assert!(
        !result.canonical_bytes.is_empty(),
        "canonical_bytes must not be empty"
    );
}

#[test]
fn ingest_av1_duration_is_1500ms() {
    // 3 frames at 2 fps = 1.5 s = 1500 ms
    let result = ingest_av1(TINY_AV1_IVF).expect("ingest_av1 should succeed");
    assert_eq!(
        result.duration_ms, 1500,
        "expected duration_ms=1500 for 3 frames at 2 fps"
    );
}

#[test]
fn ingest_av1_canonical_bytes_start_with_dkif() {
    let result = ingest_av1(TINY_AV1_IVF).expect("ingest_av1 should succeed");
    assert!(
        result.canonical_bytes.len() >= 4,
        "canonical_bytes too short to contain IVF signature"
    );
    assert_eq!(
        &result.canonical_bytes[..4],
        b"DKIF",
        "canonical_bytes must start with IVF DKIF signature"
    );
}

#[test]
fn verify_av1_roundtrip_passes_on_valid_fixture() {
    verify_av1_roundtrip(TINY_AV1_IVF)
        .expect("round-trip gate should pass on a valid AV1-IVF fixture");
}

#[test]
fn ingest_av1_is_deterministic() {
    let first = ingest_av1(TINY_AV1_IVF).expect("first ingest_av1 should succeed");
    let second = ingest_av1(TINY_AV1_IVF).expect("second ingest_av1 should succeed");
    assert_eq!(
        first.canonical_bytes, second.canonical_bytes,
        "two back-to-back ingest_av1 calls must produce byte-identical canonical_bytes"
    );
}

#[test]
fn ingest_av1_rejects_invalid_bytes() {
    let bad = b"this is not an IVF file";
    let err = ingest_av1(bad).expect_err("ingest_av1 should fail on garbage input");
    let msg = err.to_string();
    assert!(
        msg.contains("AV1 codec error"),
        "error should mention AV1: {msg}"
    );
}

#[test]
fn ingest_av1_rejects_non_av01_codec() {
    // Construct a minimal IVF header with VP90 fourcc instead of AV01.
    let mut buf = TINY_AV1_IVF.to_vec();
    // Codec fourcc is at offset 8..12.
    buf[8..12].copy_from_slice(b"VP90");
    let err = ingest_av1(&buf).expect_err("ingest_av1 should reject VP90 codec");
    let msg = err.to_string();
    assert!(
        msg.contains("AV1 codec error"),
        "error should mention AV1: {msg}"
    );
}
