/// Integration test for the FLAC codec (§5.16.13 order #2).
///
/// Verifies:
///  1. `ingest_flac` decodes the fixture and returns correct metadata.
///  2. `verify_flac_roundtrip` confirms sample-identical decode → re-encode.
///  3. Two back-to-back `ingest_flac` calls on the same bytes produce
///     byte-identical `canonical_bytes` (determinism of the encoder).
///  4. `ingest_flac` rejects garbage input.

use nom_media::{ingest_flac, verify_flac_roundtrip};

/// 8kHz mono 16-bit FLAC, 800 samples (~100 ms), generated by flacenc.
static TINY_FLAC: &[u8] = include_bytes!("fixtures/tiny.flac");

#[test]
fn ingest_flac_returns_correct_metadata() {
    let result = ingest_flac(TINY_FLAC).expect("ingest_flac should succeed on a valid FLAC");
    assert_eq!(result.sample_rate, 8000, "expected sample_rate 8000 Hz");
    assert_eq!(result.channels, 1, "expected 1 channel (mono)");
    assert_eq!(result.bits_per_sample, 16, "expected 16 bits per sample");
    assert_eq!(result.total_samples, 800, "expected 800 total samples");
    assert!(!result.canonical_bytes.is_empty(), "canonical_bytes must not be empty");
    // FLAC files begin with the magic marker "fLaC" (0x66 0x4C 0x61 0x43).
    assert_eq!(&result.canonical_bytes[..4], b"fLaC", "canonical_bytes must start with FLAC marker");
}

#[test]
fn verify_flac_roundtrip_succeeds_on_valid_flac() {
    verify_flac_roundtrip(TINY_FLAC).expect("round-trip should preserve sample content");
}

#[test]
fn ingest_flac_is_deterministic() {
    let first = ingest_flac(TINY_FLAC).expect("first ingest_flac call should succeed");
    let second = ingest_flac(TINY_FLAC).expect("second ingest_flac call should succeed");
    assert_eq!(
        first.canonical_bytes, second.canonical_bytes,
        "two back-to-back ingest_flac calls must produce byte-identical canonical_bytes"
    );
}

#[test]
fn ingest_flac_rejects_invalid_bytes() {
    let bad = b"this is not a FLAC file at all";
    let err = ingest_flac(bad).expect_err("ingest_flac should fail on garbage input");
    let msg = err.to_string();
    assert!(msg.contains("FLAC codec error"), "error should mention FLAC: {msg}");
}
