/// Integration test for the MP4/ISOBMFF container (§5.16.13 order #9).
///
/// Verifies:
///  1. `ingest_mp4` parses the ISOBMFF fixture and returns correct metadata.
///  2. `verify_mp4_roundtrip` confirms metadata round-trips cleanly.
///  3. Two back-to-back `ingest_mp4` calls on the same bytes produce
///     byte-identical `canonical_bytes` (determinism — trivially satisfied
///     by identity mapping; will still hold after a real muxer lands if the
///     muxer is deterministic at fixed settings).
///  4. `ingest_mp4` rejects garbage input.
///  5. `body_kind::MP4` constant is `"mp4"` and is a known kind.
///
/// Fixture: `tests/fixtures/tiny.mp4` — hand-crafted minimal ISOBMFF, 551 bytes.
///
/// Structure (big-endian ISOBMFF boxes):
///   ftyp  (major_brand=isom, compatible=[isom,mp41])
///   moov  →
///     mvhd  (timescale=1000, duration=500 → 500ms)
///     trak  →
///       tkhd  (track_id=1)
///       mdia  →
///         mdhd  (timescale=1000, duration=500)
///         hdlr  (handler_type=vide)
///         minf  →
///           stbl  →
///             stsd  (entry: av01)
///
/// Generated by hand-computing ISOBMFF box encodings in Python (no ffmpeg).

use nom_media::{ingest_mp4, verify_mp4_roundtrip};
use nom_types::body_kind;

static TINY_MP4: &[u8] = include_bytes!("fixtures/tiny.mp4");

#[test]
fn ingest_mp4_returns_correct_metadata() {
    let result = ingest_mp4(TINY_MP4).expect("ingest_mp4 should succeed on a valid MP4 file");
    assert_eq!(
        result.duration_ms, 500,
        "expected duration_ms 500 (500 units × 1ms timescale)"
    );
    assert_eq!(result.tracks.len(), 1, "expected 1 track");
    let track = &result.tracks[0];
    assert_eq!(track.track_id, 1, "expected track_id=1");
    assert_eq!(track.handler_type, "vide", "expected handler_type=vide");
    assert_eq!(track.codec, "av01", "expected codec=av01");
    assert!(
        !result.canonical_bytes.is_empty(),
        "canonical_bytes must not be empty"
    );
    // MP4 starts with ftyp box: size(4) + 'ftyp'(4).
    assert_eq!(&result.canonical_bytes[4..8], b"ftyp", "canonical_bytes must begin with 'ftyp' box");
}

#[test]
fn verify_mp4_roundtrip_passes() {
    verify_mp4_roundtrip(TINY_MP4)
        .expect("round-trip metadata should match (identity mapping)");
}

#[test]
fn ingest_mp4_is_deterministic() {
    let first = ingest_mp4(TINY_MP4).expect("first ingest_mp4 call should succeed");
    let second = ingest_mp4(TINY_MP4).expect("second ingest_mp4 call should succeed");
    assert_eq!(
        first.canonical_bytes, second.canonical_bytes,
        "two back-to-back ingest_mp4 calls must produce byte-identical canonical_bytes"
    );
}

#[test]
fn ingest_mp4_rejects_invalid_bytes() {
    let bad = b"this is not an MP4 file at all!!";
    let err = ingest_mp4(bad).expect_err("ingest_mp4 should fail on garbage input");
    let msg = err.to_string();
    assert!(
        msg.contains("MP4 codec error"),
        "error should mention MP4: {msg}"
    );
}

#[test]
fn mp4_body_kind_constant_is_known() {
    assert_eq!(body_kind::MP4, "mp4");
    assert!(
        body_kind::is_known(body_kind::MP4),
        "body_kind::MP4 must be recognized by is_known"
    );
}
