/// Integration test for the Opus codec (§5.16.13 order #4).
///
/// Verifies:
///  1. `ingest_opus` decodes the fixture and returns correct metadata.
///  2. `verify_opus_roundtrip` confirms audio SNR ≥ 20 dB (lossy round-trip gate).
///  3. Two back-to-back `ingest_opus` calls on the same bytes produce
///     byte-identical `canonical_bytes` (determinism — trivially satisfied
///     by identity mapping; will still hold after a real encoder lands if
///     the encoder is deterministic at fixed settings).
///  4. `ingest_opus` rejects garbage input.
///  5. `ingest_opus` body_kind constant is "opus" and is a known kind.

use nom_media::{ingest_opus, verify_opus_roundtrip};
use nom_types::body_kind;

/// Minimal Ogg-Opus file: 8 kHz mono, 3 × 20 ms silence frames (~60 ms).
/// Generated by Python using the Ogg/Opus RFC 7845 wire format.
static TINY_OPUS: &[u8] = include_bytes!("fixtures/tiny.opus");

#[test]
fn ingest_opus_returns_correct_metadata() {
    let result = ingest_opus(TINY_OPUS).expect("ingest_opus should succeed on a valid Ogg-Opus");
    assert_eq!(result.sample_rate, 8000, "expected sample_rate 8000 Hz");
    assert_eq!(result.channels, 1, "expected 1 channel (mono)");
    assert!(
        !result.canonical_bytes.is_empty(),
        "canonical_bytes must not be empty"
    );
    // Ogg files begin with the capture pattern "OggS".
    assert_eq!(
        &result.canonical_bytes[..4],
        b"OggS",
        "canonical_bytes must start with Ogg capture pattern"
    );
}

#[test]
fn verify_opus_roundtrip_passes_snr_gate() {
    verify_opus_roundtrip(TINY_OPUS)
        .expect("round-trip audio SNR should be ≥ 20 dB (identity mapping → infinite SNR)");
}

#[test]
fn ingest_opus_is_deterministic() {
    let first = ingest_opus(TINY_OPUS).expect("first ingest_opus call should succeed");
    let second = ingest_opus(TINY_OPUS).expect("second ingest_opus call should succeed");
    assert_eq!(
        first.canonical_bytes, second.canonical_bytes,
        "two back-to-back ingest_opus calls must produce byte-identical canonical_bytes"
    );
}

#[test]
fn ingest_opus_rejects_invalid_bytes() {
    let bad = b"this is not an Ogg-Opus file at all";
    let err = ingest_opus(bad).expect_err("ingest_opus should fail on garbage input");
    let msg = err.to_string();
    assert!(
        msg.contains("Opus codec error"),
        "error should mention Opus: {msg}"
    );
}

#[test]
fn opus_body_kind_constant_is_known() {
    assert_eq!(body_kind::OPUS, "opus");
    assert!(
        body_kind::is_known(body_kind::OPUS),
        "body_kind::OPUS must be recognized by is_known"
    );
}
