/// Integration test for the WebM/Matroska container (§5.16.13 order #8).
///
/// Verifies:
///  1. `ingest_webm` parses the EBML fixture and returns correct metadata.
///  2. `verify_webm_roundtrip` confirms metadata round-trips cleanly.
///  3. Two back-to-back `ingest_webm` calls on the same bytes produce
///     byte-identical `canonical_bytes` (determinism — trivially satisfied
///     by identity mapping; will still hold after a real muxer lands if the
///     muxer is deterministic at fixed settings).
///  4. `ingest_webm` rejects garbage input.
///  5. `body_kind::WEBM` constant is `"webm"` and is a known kind.
///
/// Fixture: `tests/fixtures/tiny.webm` — hand-crafted minimal WebM,
/// 101 bytes.
///
/// Structure (all EBML big-endian):
///   EBML header (DocType="webm", version 4)
///   Segment →
///     SegmentInfo  (TimecodeScale=1_000_000ns, Duration=500.0 units → 500ms)
///     Tracks →
///       TrackEntry (TrackNumber=1, TrackType=1=video,  CodecID="V_AV1")
///       TrackEntry (TrackNumber=2, TrackType=2=audio,  CodecID="A_OPUS")
///
/// Generated by hand-computing EBML element encodings in Python (no ffmpeg).

use nom_media::{ingest_webm, verify_webm_roundtrip};
use nom_types::body_kind;

static TINY_WEBM: &[u8] = include_bytes!("fixtures/tiny.webm");

#[test]
fn ingest_webm_returns_correct_metadata() {
    let result = ingest_webm(TINY_WEBM).expect("ingest_webm should succeed on a valid WebM file");
    assert_eq!(
        result.duration_ms, 500,
        "expected duration_ms 500 (500.0 units × 1ms scale)"
    );
    assert_eq!(result.tracks.len(), 2, "expected 2 tracks");
    let track_types: Vec<&str> = result.tracks.iter().map(|t| t.track_type.as_str()).collect();
    assert!(
        track_types.contains(&"video"),
        "expected a video track; got {track_types:?}"
    );
    assert!(
        track_types.contains(&"audio"),
        "expected an audio track; got {track_types:?}"
    );
    let codec_ids: Vec<&str> = result.tracks.iter().map(|t| t.codec_id.as_str()).collect();
    assert!(codec_ids.contains(&"V_AV1"), "expected V_AV1 codec; got {codec_ids:?}");
    assert!(codec_ids.contains(&"A_OPUS"), "expected A_OPUS codec; got {codec_ids:?}");
    assert!(
        !result.canonical_bytes.is_empty(),
        "canonical_bytes must not be empty"
    );
    // WebM starts with EBML magic 0x1A 0x45 0xDF 0xA3.
    assert_eq!(result.canonical_bytes[0], 0x1A, "canonical_bytes[0] must be 0x1A (EBML magic)");
    assert_eq!(result.canonical_bytes[1], 0x45, "canonical_bytes[1] must be 0x45 (EBML magic)");
}

#[test]
fn verify_webm_roundtrip_passes() {
    verify_webm_roundtrip(TINY_WEBM)
        .expect("round-trip metadata should match (identity mapping)");
}

#[test]
fn ingest_webm_is_deterministic() {
    let first = ingest_webm(TINY_WEBM).expect("first ingest_webm call should succeed");
    let second = ingest_webm(TINY_WEBM).expect("second ingest_webm call should succeed");
    assert_eq!(
        first.canonical_bytes, second.canonical_bytes,
        "two back-to-back ingest_webm calls must produce byte-identical canonical_bytes"
    );
}

#[test]
fn ingest_webm_rejects_invalid_bytes() {
    let bad = b"this is not a WebM file at all";
    let err = ingest_webm(bad).expect_err("ingest_webm should fail on garbage input");
    let msg = err.to_string();
    assert!(
        msg.contains("WebM codec error"),
        "error should mention WebM: {msg}"
    );
}

#[test]
fn webm_body_kind_constant_is_known() {
    assert_eq!(body_kind::WEBM, "webm");
    assert!(
        body_kind::is_known(body_kind::WEBM),
        "body_kind::WEBM must be recognized by is_known"
    );
}
