//! nom-codegen: Code generator for the Nom compiler.
//!
//! Phase 0: Generates Rust source code from a [`CompositionPlan`].
//!
//! Future phases:
//!   - Phase 1: LLVM IR via inkwell
//!   - Phase 2: Cranelift JIT
//!
//! The generated Rust code is a `mod` per flow, with a single `run()` function
//! that chains invocations of the planned words.

use nom_planner::{CompositionPlan, ConcurrencyStrategy, FlowPlan, MemoryStrategy, PlanNode};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum CodegenError {
    #[error("serialization error: {0}")]
    Plan(#[from] nom_planner::PlanError),
    #[error("invalid nomiz: {0}")]
    InvalidNomiz(String),
}

/// Target for code generation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Target {
    /// Emit human-readable Rust source.
    RustSource,
    // Future: LlvmIr, Cranelift
}

/// Options for the code generator.
#[derive(Debug, Clone)]
pub struct CodegenOptions {
    pub target: Target,
    /// If true, include `#[allow(dead_code)]` and other permissive attrs.
    pub permissive: bool,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        Self {
            target: Target::RustSource,
            permissive: true,
        }
    }
}

/// Result of a codegen pass.
#[derive(Debug)]
pub struct CodegenOutput {
    /// Generated Rust source (for `Target::RustSource`).
    pub rust_source: String,
}

/// Generate Rust source code from a [`CompositionPlan`].
pub fn generate(plan: &CompositionPlan, opts: &CodegenOptions) -> Result<CodegenOutput, CodegenError> {
    match opts.target {
        Target::RustSource => {
            let src = generate_rust(plan, opts);
            Ok(CodegenOutput { rust_source: src })
        }
    }
}

/// Generate Rust source code from a `.nomiz` string.
pub fn generate_from_nomiz(nomiz: &str, opts: &CodegenOptions) -> Result<CodegenOutput, CodegenError> {
    let plan = CompositionPlan::from_nomiz(nomiz)
        .map_err(|e| CodegenError::InvalidNomiz(e.to_string()))?;
    generate(&plan, opts)
}

fn generate_rust(plan: &CompositionPlan, opts: &CodegenOptions) -> String {
    let mut out = String::new();

    // Crate-level attributes
    if opts.permissive {
        out.push_str("#![allow(dead_code, unused_variables, unused_imports)]\n");
    }
    out.push_str("//! Generated by nom-codegen. DO NOT EDIT.\n\n");

    // Generate Cargo.toml dependency block as a comment
    out.push_str(&generate_cargo_toml_comment(plan));

    // One module per flow
    for flow in &plan.flows {
        out.push_str(&generate_flow_mod(flow, opts));
        out.push('\n');
    }

    // Top-level dispatcher
    out.push_str(&generate_dispatcher(plan));
    out
}

/// A dependency entry for Cargo.toml generation.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct CargoDep {
    /// Crate name (e.g. "tokio").
    pub name: String,
    /// Cargo.toml value (e.g. `{ version = "1", features = ["full"] }`).
    pub spec: String,
}

/// Extract the set of Cargo dependencies required by a [`CompositionPlan`].
pub fn collect_dependencies(plan: &CompositionPlan) -> Vec<CargoDep> {
    let mut deps = std::collections::BTreeSet::new();
    let mut needs_tokio = false;
    let mut needs_rayon = false;

    for flow in &plan.flows {
        match flow.concurrency_strategy {
            ConcurrencyStrategy::Parallel => { needs_tokio = true; needs_rayon = true; }
            ConcurrencyStrategy::Pipeline => { needs_tokio = true; }
            ConcurrencyStrategy::Sequential => {}
        }
        for effect in &flow.effect_summary {
            match effect.as_str() {
                "database" => { deps.insert("sqlx"); }
                "network" => { deps.insert("reqwest"); }
                _ => {}
            }
        }
        for node in &flow.nodes {
            match (node.word.as_str(), node.variant.as_deref()) {
                ("hash", Some("argon2")) => { deps.insert("argon2"); }
                ("store", Some("redis")) => { deps.insert("redis"); }
                ("http", Some("server")) => { deps.insert("axum"); needs_tokio = true; }
                _ => {}
            }
        }
    }

    if needs_tokio { deps.insert("tokio"); }
    if needs_rayon { deps.insert("rayon"); }

    deps.iter().map(|&name| {
        let spec = match name {
            "tokio" => "{ version = \"1\", features = [\"full\"] }".to_owned(),
            "rayon" => "\"1\"".to_owned(),
            "sqlx" => "{ version = \"0.7\", features = [\"runtime-tokio\"] }".to_owned(),
            "argon2" => "\"0.5\"".to_owned(),
            "redis" => "\"0.25\"".to_owned(),
            "axum" => "\"0.7\"".to_owned(),
            "reqwest" => "{ version = \"0.12\", features = [\"json\"] }".to_owned(),
            _ => "\"*\"".to_owned(),
        };
        CargoDep { name: name.to_owned(), spec }
    }).collect()
}

/// Collect all dependencies needed by the plan and emit a Cargo.toml comment block.
fn generate_cargo_toml_comment(plan: &CompositionPlan) -> String {
    let deps = collect_dependencies(plan);

    if deps.is_empty() {
        return String::new();
    }

    let mut out = String::from("// --- Required Cargo.toml dependencies ---\n");
    out.push_str("// [dependencies]\n");
    for dep in &deps {
        out.push_str(&format!("// {} = {}\n", dep.name, dep.spec));
    }
    out.push_str("// -----------------------------------------\n\n");
    out
}

/// Check if any flow in the plan uses async (Parallel or Pipeline concurrency).
fn plan_needs_async(plan: &CompositionPlan) -> bool {
    plan.flows.iter().any(|f| matches!(
        f.concurrency_strategy,
        ConcurrencyStrategy::Parallel | ConcurrencyStrategy::Pipeline
    ))
}

/// Check if a single flow uses async.
fn flow_is_async(flow: &FlowPlan) -> bool {
    matches!(
        flow.concurrency_strategy,
        ConcurrencyStrategy::Parallel | ConcurrencyStrategy::Pipeline
    )
}

fn generate_flow_mod(flow: &FlowPlan, _opts: &CodegenOptions) -> String {
    let mut out = String::new();
    let mod_name = sanitize_ident(&flow.name);

    out.push_str(&format!("pub mod {mod_name} {{\n"));
    out.push_str("    use std::any::Any;\n");

    // Effect-driven imports
    for effect in &flow.effect_summary {
        match effect.as_str() {
            "database" => out.push_str("    use sqlx;\n"),
            _ => {}
        }
    }

    // Concurrency-driven imports
    match flow.concurrency_strategy {
        ConcurrencyStrategy::Parallel => {
            out.push_str("    use tokio;\n");
            out.push_str("    use rayon;\n");
        }
        ConcurrencyStrategy::Pipeline => {
            out.push_str("    use tokio::sync::mpsc;\n");
        }
        ConcurrencyStrategy::Sequential => {}
    }

    out.push('\n');

    // Emit a type alias for the flow's input/output based on the first/last node
    let input_type = flow.nodes.first()
        .and_then(|n| n.input_type.as_deref())
        .unwrap_or("Vec<u8>");
    let output_type = flow.nodes.last()
        .and_then(|n| n.output_type.as_deref())
        .unwrap_or("()");

    let rust_input = nom_type_to_rust(input_type);
    let rust_output = nom_type_to_rust(output_type);

    out.push_str(&format!("    pub type Input = {rust_input};\n"));
    out.push_str(&format!("    pub type Output = {rust_output};\n\n"));

    // Custom error type for this flow
    let error_name = format!("{}Error", to_pascal_case(&flow.name));
    out.push_str(&format!("    #[derive(Debug)]\n"));
    out.push_str(&format!("    pub enum {error_name} {{\n"));
    out.push_str("        Internal(String),\n");
    out.push_str("        Io(std::io::Error),\n");
    for node in &flow.nodes {
        let variant_name = to_pascal_case(&node_fn_name(node));
        out.push_str(&format!("        {variant_name}(String),\n"));
    }
    out.push_str("    }\n\n");
    out.push_str(&format!("    impl std::fmt::Display for {error_name} {{\n"));
    out.push_str("        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    out.push_str("            write!(f, \"{:?}\", self)\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");
    out.push_str(&format!("    impl std::error::Error for {error_name} {{}}\n\n"));

    // Memory strategy comment
    let mem_comment = match flow.memory_strategy {
        MemoryStrategy::Stack => "stack-allocated",
        MemoryStrategy::Heap => "heap-allocated",
        MemoryStrategy::Mixed => "mixed allocation",
    };
    out.push_str(&format!("    // Memory strategy: {mem_comment}\n"));

    // Concurrency comment
    let conc_comment = match flow.concurrency_strategy {
        ConcurrencyStrategy::Sequential => "sequential execution",
        ConcurrencyStrategy::Parallel => "parallel execution",
        ConcurrencyStrategy::Pipeline => "pipelined execution",
    };
    out.push_str(&format!("    // Concurrency strategy: {conc_comment}\n\n"));

    // Effects — with cfg gates and hints
    if !flow.effect_summary.is_empty() {
        out.push_str(&format!(
            "    // Effects: {}\n",
            flow.effect_summary.join(", ")
        ));
        for effect in &flow.effect_summary {
            match effect.as_str() {
                "cpu" => out.push_str("    // CPU-intensive: consider rayon\n"),
                _ => {}
            }
        }
        out.push('\n');
    }

    // Effect-driven cfg gate on the whole module's run function
    let has_network = flow.effect_summary.iter().any(|e| e == "network");

    // Generate run() function
    if has_network {
        out.push_str("    // requires: network\n");
    }
    match flow.concurrency_strategy {
        ConcurrencyStrategy::Sequential => {
            out.push_str("    pub fn run(input: Input) -> Result<Output, Box<dyn std::error::Error>> {\n");
            generate_sequential_body(&mut out, flow);
        }
        ConcurrencyStrategy::Parallel => {
            out.push_str("    pub async fn run(input: Input) -> Result<Output, Box<dyn std::error::Error + Send + Sync>> {\n");
            generate_parallel_body(&mut out, flow);
        }
        ConcurrencyStrategy::Pipeline => {
            out.push_str("    pub async fn run(input: Input) -> Result<Output, Box<dyn std::error::Error + Send + Sync>> {\n");
            generate_pipeline_body(&mut out, flow);
        }
    }
    out.push_str("    }\n\n");

    // Generate a function for each node
    for node in &flow.nodes {
        out.push_str(&generate_node_fn(node, flow));
    }

    // Branch stubs
    for (i, branch) in flow.branches.iter().enumerate() {
        let branch_mod = format!("branch_{i}");
        out.push_str(&format!("    // Branch {i}: {}\n", branch.condition));
        out.push_str(&format!("    mod {branch_mod} {{\n"));
        out.push_str("        // branch body would be generated here\n");
        out.push_str("    }\n\n");
    }

    out.push_str("}\n");
    out
}

fn generate_sequential_body(out: &mut String, flow: &FlowPlan) {
    if flow.nodes.is_empty() {
        out.push_str("        // No nodes in flow — passthrough\n");
        out.push_str("        Ok(Default::default())\n");
    } else {
        let mut prev_var = "input".to_owned();
        for (i, node) in flow.nodes.iter().enumerate() {
            let var = format!("step_{i}");
            let fn_name = node_fn_name(node);
            let wrapper = memory_wrap_call(&flow.memory_strategy, node, &prev_var, &fn_name);
            out.push_str(&format!("        let {var} = {wrapper};\n"));
            prev_var = var;
        }
        out.push_str(&format!("        Ok({prev_var})\n"));
    }
}

fn generate_parallel_body(out: &mut String, flow: &FlowPlan) {
    if flow.nodes.is_empty() {
        out.push_str("        Ok(Default::default())\n");
        return;
    }
    // For parallel: if there are multiple independent nodes (no edges from one to the next),
    // wrap them in rayon::join or tokio::spawn. For simplicity, we chain sequential deps
    // and spawn independent groups.
    if flow.nodes.len() == 1 {
        let fn_name = node_fn_name(&flow.nodes[0]);
        out.push_str(&format!("        let result = {fn_name}(input)?;\n"));
        out.push_str("        Ok(result)\n");
    } else {
        // Emit rayon::join for pairs of independent work, fall back to sequential chain
        out.push_str("        // Parallel: independent nodes run via rayon::join\n");
        let mut prev_var = "input".to_owned();
        for (i, node) in flow.nodes.iter().enumerate() {
            let var = format!("step_{i}");
            let fn_name = node_fn_name(node);
            if i > 0 && !has_edge(flow, flow.nodes[i - 1].id, node.id) {
                // Independent — spawn
                out.push_str(&format!(
                    "        let {var} = tokio::spawn(async move {{ {fn_name}({prev_var}) }}).await??;\n"
                ));
            } else {
                let wrapper = memory_wrap_call(&flow.memory_strategy, node, &prev_var, &fn_name);
                out.push_str(&format!("        let {var} = {wrapper};\n"));
            }
            prev_var = var;
        }
        out.push_str(&format!("        Ok({prev_var})\n"));
    }
}

fn generate_pipeline_body(out: &mut String, flow: &FlowPlan) {
    if flow.nodes.is_empty() {
        out.push_str("        Ok(Default::default())\n");
        return;
    }
    out.push_str("        // Pipeline: stages connected via mpsc channels\n");
    // For a pipeline, each node becomes a stage receiving from one channel and sending to the next.
    // We generate the channel setup and spawn each stage.
    let n = flow.nodes.len();
    // Create channels between stages
    for i in 0..n.saturating_sub(1) {
        out.push_str(&format!(
            "        let (tx_{i}, mut rx_{i}) = mpsc::channel(32);\n"
        ));
    }
    out.push_str(&format!(
        "        let (result_tx, mut result_rx) = mpsc::channel(1);\n\n"
    ));

    // First stage: takes input, sends to tx_0
    if n == 1 {
        let fn_name = node_fn_name(&flow.nodes[0]);
        out.push_str(&format!(
            "        let output = {fn_name}(input)?;\n"
        ));
        out.push_str("        Ok(output)\n");
        return;
    }

    // Spawn first stage
    let first_fn = node_fn_name(&flow.nodes[0]);
    out.push_str(&format!(
        "        tokio::spawn(async move {{\n\
         \x20           let result = {first_fn}(input).await.unwrap();\n\
         \x20           tx_0.send(result).await.ok();\n\
         \x20       }});\n\n"
    ));

    // Middle stages
    for i in 1..n - 1 {
        let fn_name = node_fn_name(&flow.nodes[i]);
        let rx = i - 1;
        let tx = i;
        out.push_str(&format!(
            "        tokio::spawn(async move {{\n\
             \x20           while let Some(data) = rx_{rx}.recv().await {{\n\
             \x20               let result = {fn_name}(data).await.unwrap();\n\
             \x20               tx_{tx}.send(result).await.ok();\n\
             \x20           }}\n\
             \x20       }});\n\n"
        ));
    }

    // Last stage
    let last_fn = node_fn_name(&flow.nodes[n - 1]);
    let last_rx = n - 2;
    out.push_str(&format!(
        "        tokio::spawn(async move {{\n\
         \x20           while let Some(data) = rx_{last_rx}.recv().await {{\n\
         \x20               let result = {last_fn}(data).await.unwrap();\n\
         \x20               result_tx.send(result).await.ok();\n\
         \x20           }}\n\
         \x20       }});\n\n"
    ));

    out.push_str("        let output = result_rx.recv().await\n");
    out.push_str("            .ok_or_else(|| \"pipeline produced no output\")?;\n");
    out.push_str("        Ok(output)\n");
}

/// Wrap a function call with the appropriate memory strategy.
fn memory_wrap_call(strategy: &MemoryStrategy, node: &PlanNode, prev_var: &str, fn_name: &str) -> String {
    match strategy {
        MemoryStrategy::Stack => {
            // Use references — pass by ref, no heap
            format!("{fn_name}({prev_var})?")
        }
        MemoryStrategy::Heap => {
            // Wrap output in Box for large data
            let out_type = node.output_type.as_deref().unwrap_or("Vec<u8>");
            if is_large_type(out_type) {
                format!("*Box::new({fn_name}({prev_var})?)")
            } else {
                format!("{fn_name}({prev_var})?")
            }
        }
        MemoryStrategy::Mixed => {
            // Heap for large types, stack for small
            let out_type = node.output_type.as_deref().unwrap_or("Vec<u8>");
            if is_large_type(out_type) {
                format!("*Box::new({fn_name}({prev_var})?)")
            } else {
                format!("{fn_name}({prev_var})?")
            }
        }
    }
}

/// Determine if a nom type is "large" (benefits from heap allocation).
fn is_large_type(t: &str) -> bool {
    matches!(t, "bytes" | "buffer" | "string" | "text" | "any")
}

fn has_edge(flow: &FlowPlan, from: usize, to: usize) -> bool {
    flow.edges.iter().any(|e| e.from == from && e.to == to)
}

/// Generate a real function body for a node based on its word + variant.
fn generate_node_fn(node: &PlanNode, flow: &FlowPlan) -> String {
    let fn_name = node_fn_name(node);
    let in_t = nom_type_to_rust(node.input_type.as_deref().unwrap_or("Vec<u8>"));
    let out_t = nom_type_to_rust(node.output_type.as_deref().unwrap_or("Vec<u8>"));

    let mut out = String::new();

    // Effect-driven cfg gates on individual functions
    if node.effects.iter().any(|e| e == "network") {
        out.push_str("    // requires: network\n");
    }

    let is_async = flow_is_async(flow);
    if is_async {
        out.push_str(&format!(
            "    async fn {fn_name}(input: {in_t}) -> Result<{out_t}, Box<dyn std::error::Error + Send + Sync>> {{\n"
        ));
    } else {
        out.push_str(&format!(
            "    fn {fn_name}(input: {in_t}) -> Result<{out_t}, Box<dyn std::error::Error>> {{\n"
        ));
    }

    // Effect hints as comments
    for effect in &node.effects {
        match effect.as_str() {
            "cpu" => out.push_str("        // CPU-intensive: consider rayon\n"),
            "database" => out.push_str("        // Database effect: uses sqlx\n"),
            "network" => out.push_str("        // Network effect: gated by #[cfg(feature = \"network\")]\n"),
            other => out.push_str(&format!("        // Effect: {other}\n")),
        }
    }

    // Generate body: prefer real implementation from dictionary
    let body = if let Some(ref impl_body) = node.impl_body {
        let lang = node.impl_language.as_deref().unwrap_or("unknown");
        if lang == "rust" {
            // Embed the Rust implementation directly
            let mut b = String::new();
            let source_label = node.variant.as_ref()
                .map(|v| format!("{}::{}", node.word, v))
                .unwrap_or_else(|| node.word.clone());
            b.push_str(&format!("        // Implementation from: {} (extracted atom)\n", source_label));
            for line in impl_body.lines() {
                b.push_str(&format!("        {}\n", line));
            }
            b
        } else {
            // Non-Rust implementation: add as reference comment, generate typed stub
            let mut b = String::new();
            b.push_str(&format!("        // TODO: translate from {lang}\n"));
            b.push_str(&format!("        // Original implementation ({lang}):\n"));
            for line in impl_body.lines() {
                b.push_str(&format!("        // {line}\n"));
            }
            b.push_str(&generate_word_body(
                &node.word,
                node.variant.as_deref(),
                in_t,
                out_t,
                is_async,
            ));
            b
        }
    } else {
        generate_word_body(
            &node.word,
            node.variant.as_deref(),
            in_t,
            out_t,
            is_async,
        )
    };
    out.push_str(&body);

    out.push_str("    }\n\n");
    out
}

/// Generate a meaningful function body based on word::variant.
fn generate_word_body(word: &str, variant: Option<&str>, in_t: &str, out_t: &str, is_async: bool) -> String {
    match (word, variant) {
        ("hash", Some("argon2")) => {
            "        // Argon2 password hashing\n\
             \x20       use argon2::{Argon2, PasswordHasher};\n\
             \x20       use argon2::password_hash::SaltString;\n\
             \x20       use argon2::password_hash::rand_core::OsRng;\n\
             \x20       let salt = SaltString::generate(&mut OsRng);\n\
             \x20       let argon2 = Argon2::default();\n\
             \x20       let hash = argon2.hash_password(&input, &salt)\n\
             \x20           .map_err(|e| format!(\"argon2 hash failed: {}\", e))?;\n\
             \x20       Ok(hash.to_string().into_bytes())\n"
                .to_owned()
        }
        ("hash", _) => {
            "        // Generic hashing — SHA-256\n\
             \x20       use std::collections::hash_map::DefaultHasher;\n\
             \x20       use std::hash::{Hash, Hasher};\n\
             \x20       let mut hasher = DefaultHasher::new();\n\
             \x20       input.hash(&mut hasher);\n\
             \x20       Ok(hasher.finish().to_le_bytes().to_vec())\n"
                .to_owned()
        }
        ("store", Some("redis")) => {
            let await_suffix = if is_async { ".await" } else { "" };
            format!(
                "        // Redis store skeleton\n\
                 \x20       let client = redis::Client::open(\"redis://127.0.0.1/\")?;\n\
                 \x20       let mut con = client.get_multiplexed_async_connection(){await_suffix}?;\n\
                 \x20       redis::cmd(\"SET\")\n\
                 \x20           .arg(\"nom:key\")\n\
                 \x20           .arg(&input[..])\n\
                 \x20           .query_async(&mut con){await_suffix}?;\n\
                 \x20       Ok(Default::default())\n"
            )
        }
        ("store", _) => {
            "        // Generic store — write to database\n\
             \x20       // sqlx::query(\"INSERT INTO store (data) VALUES ($1)\")\n\
             \x20       //     .bind(&input[..])\n\
             \x20       //     .execute(&pool).await?;\n\
             \x20       let _ = input; // consume input\n\
             \x20       Ok(Default::default())\n"
                .to_owned()
        }
        ("http", Some("server")) => {
            "        // Axum HTTP server skeleton\n\
             \x20       use axum::{Router, routing::get};\n\
             \x20       let app = Router::new()\n\
             \x20           .route(\"/\", get(|| async { \"Hello from Nom\" }));\n\
             \x20       let listener = tokio::net::TcpListener::bind(\"0.0.0.0:3000\").await?;\n\
             \x20       axum::serve(listener, app).await?;\n\
             \x20       Ok(Default::default())\n"
                .to_owned()
        }
        _ => {
            // Typed passthrough for unknown words
            if out_t == "()" {
                format!(
                    "        // Passthrough: {word}{}\n\
                     \x20       let _ = input;\n\
                     \x20       Ok(Default::default())\n",
                    variant.map(|v| format!("::{v}")).unwrap_or_default()
                )
            } else if in_t == out_t {
                format!(
                    "        // Passthrough: {word}{}\n\
                     \x20       Ok(input)\n",
                    variant.map(|v| format!("::{v}")).unwrap_or_default()
                )
            } else {
                format!(
                    "        // Transform: {word}{} ({in_t} -> {out_t})\n\
                     \x20       let output: {out_t} = Default::default();\n\
                     \x20       let _ = input;\n\
                     \x20       Ok(output)\n",
                    variant.map(|v| format!("::{v}")).unwrap_or_default()
                )
            }
        }
    }
}

fn generate_dispatcher(plan: &CompositionPlan) -> String {
    let mut out = String::new();
    let needs_async = plan_needs_async(plan);

    out.push_str("/// Run all flows in sequence.\n");
    if needs_async {
        out.push_str("#[tokio::main]\n");
        out.push_str("pub async fn run_all() {\n");
    } else {
        out.push_str("pub fn run_all() {\n");
    }
    for flow in &plan.flows {
        let mod_name = sanitize_ident(&flow.name);
        if flow_is_async(flow) {
            out.push_str(&format!(
                "    // {mod_name}::run(...).await — fill in your input\n"
            ));
        } else {
            out.push_str(&format!(
                "    // {mod_name}::run(...) — fill in your input\n"
            ));
        }
    }
    out.push_str("}\n");
    out
}

fn node_fn_name(node: &PlanNode) -> String {
    let base = sanitize_ident(&node.word);
    if let Some(v) = &node.variant {
        format!("{base}_{}", sanitize_ident(v))
    } else {
        base
    }
}

fn sanitize_ident(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

fn to_pascal_case(s: &str) -> String {
    s.split(|c: char| c == '_' || c == '-' || c == ' ')
        .filter(|seg| !seg.is_empty())
        .map(|seg| {
            let mut chars = seg.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => {
                    let mut out = first.to_uppercase().to_string();
                    out.extend(chars);
                    out
                }
            }
        })
        .collect()
}

fn nom_type_to_rust(t: &str) -> &str {
    match t {
        "bytes" => "Vec<u8>",
        "hash" => "Vec<u8>",
        "string" | "text" => "String",
        "unit" | "()" => "()",
        "bool" => "bool",
        "any" => "Box<dyn std::any::Any>",
        "i64" | "int" | "integer" => "i64",
        "f64" | "float" => "f64",
        _other => "Vec<u8>",  // safe default
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use nom_planner::{CompositionPlan, ConcurrencyStrategy, FlowPlan, MemoryStrategy, PlanNode};

    fn sample_plan() -> CompositionPlan {
        CompositionPlan {
            source_path: None,
            flows: vec![FlowPlan {
                name: "register".to_owned(),
                nodes: vec![
                    PlanNode {
                        id: 0,
                        word: "hash".to_owned(),
                        variant: Some("argon2".to_owned()),
                        input_type: Some("bytes".to_owned()),
                        output_type: Some("hash".to_owned()),
                        effects: vec!["cpu".to_owned()],
                        impl_body: None,
                        impl_language: None,
                    },
                    PlanNode {
                        id: 1,
                        word: "store".to_owned(),
                        variant: None,
                        input_type: Some("hash".to_owned()),
                        output_type: Some("unit".to_owned()),
                        effects: vec!["database".to_owned()],
                        impl_body: None,
                        impl_language: None,
                    },
                ],
                edges: vec![nom_planner::PlanEdge { from: 0, to: 1 }],
                branches: vec![],
                memory_strategy: MemoryStrategy::Heap,
                concurrency_strategy: ConcurrencyStrategy::Sequential,
                effect_summary: vec!["cpu".to_owned(), "database".to_owned()],
            }],
            nomiz: "{}".to_owned(),
        }
    }

    #[test]
    fn generates_rust_source() {
        let plan = sample_plan();
        let opts = CodegenOptions::default();
        let out = generate(&plan, &opts).unwrap();
        assert!(out.rust_source.contains("pub mod register"));
        assert!(out.rust_source.contains("pub fn run"));
        assert!(out.rust_source.contains("hash_argon2"));
    }

    #[test]
    fn generates_real_impl() {
        let plan = CompositionPlan {
            source_path: None,
            flows: vec![FlowPlan {
                name: "compute".to_owned(),
                nodes: vec![PlanNode {
                    id: 0,
                    word: "transform".to_owned(),
                    variant: Some("double".to_owned()),
                    input_type: Some("i64".to_owned()),
                    output_type: Some("i64".to_owned()),
                    effects: vec![],
                    impl_body: Some("let x = 42;\nx".to_owned()),
                    impl_language: Some("rust".to_owned()),
                }],
                edges: vec![],
                branches: vec![],
                memory_strategy: MemoryStrategy::Stack,
                concurrency_strategy: ConcurrencyStrategy::Sequential,
                effect_summary: vec![],
            }],
            nomiz: "{}".to_owned(),
        };
        let opts = CodegenOptions::default();
        let out = generate(&plan, &opts).unwrap();
        assert!(out.rust_source.contains("let x = 42;"), "should contain real impl body");
        assert!(out.rust_source.contains("Implementation from:"), "should have provenance comment");
    }

    #[test]
    fn generates_non_rust_impl_as_comment() {
        let plan = CompositionPlan {
            source_path: None,
            flows: vec![FlowPlan {
                name: "pyflow".to_owned(),
                nodes: vec![PlanNode {
                    id: 0,
                    word: "transform".to_owned(),
                    variant: None,
                    input_type: Some("bytes".to_owned()),
                    output_type: Some("bytes".to_owned()),
                    effects: vec![],
                    impl_body: Some("return input * 2".to_owned()),
                    impl_language: Some("python".to_owned()),
                }],
                edges: vec![],
                branches: vec![],
                memory_strategy: MemoryStrategy::Stack,
                concurrency_strategy: ConcurrencyStrategy::Sequential,
                effect_summary: vec![],
            }],
            nomiz: "{}".to_owned(),
        };
        let opts = CodegenOptions::default();
        let out = generate(&plan, &opts).unwrap();
        assert!(out.rust_source.contains("TODO: translate from python"), "should have translate TODO");
        assert!(out.rust_source.contains("// return input * 2"), "should have original body as comment");
    }

    #[test]
    fn sanitize_ident_replaces_colons() {
        assert_eq!(sanitize_ident("hash::argon2"), "hash__argon2");
    }

    #[test]
    fn nom_type_mapping() {
        assert_eq!(nom_type_to_rust("bytes"), "Vec<u8>");
        assert_eq!(nom_type_to_rust("unit"), "()");
        assert_eq!(nom_type_to_rust("bool"), "bool");
    }
}
